name: Daddylive Scraper

# Bu action'ı ne zaman çalıştıracağını belirleyen tetikleyiciler
on:
  # Her 6 saatte bir otomatik olarak çalıştırır (Cron zamanlamasını değiştirebilirsiniz)
  schedule:
    - cron: '0 */6 * * *'
    
  # GitHub Actions arayüzünden "Run workflow" butonu ile manuel olarak çalıştırmayı sağlar
  workflow_dispatch:

jobs:
  scrape:
    # Action'ın çalışacağı sanal makineyi belirtir
    runs-on: ubuntu-latest

    steps:
      # 1. Adım: Proje dosyalarını indir
      # Action'ın çalışacağı sanal makineye kodlarınızı kopyalar
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Adım: Python'u kur
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # İstediğiniz Python sürümünü kullanabilirsiniz

      # 3. Adım: Google Chrome'u kur (Selenium için gerekli)
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 4. Adım: Python kütüphanelerini kur
      # requirements.txt dosyasındaki kütüphaneleri yükler
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 5. Adım: Scraper script'ini çalıştır
      # Önceki cevapta verdiğim güncellenmiş scraper.py kodunu çalıştırır
      - name: Run the scraper script
        run: python scraper.py

      # 6. Adım: Güncellenen dosyaları repoya geri yükle
      # Oluşturulan out.m3u8 ve url_cache.json dosyalarını otomatik olarak repoya commit'ler.
      # Böylece M3U8 linkiniz her zaman güncel kalır.
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add out.m3u8 url_cache.json
          # Dosyalarda değişiklik varsa commit at ve ana dala (main/master) push'la
          git diff --staged --quiet || (git commit -m "Update m3u8 playlist and cache" && git push)
