name: Build M3U8 Playlist

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ----------------------
      # Checkout repo with push permissions
      # ----------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ensures push permission

      # ----------------------
      # Setup Python
      # ----------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # ----------------------
      # Install dependencies
      # ----------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # ----------------------
      # Determine scraper folder
      # ----------------------
      - name: Determine script folder
        id: folder
        run: |
          if [ -f "$GITHUB_WORKSPACE/scraper.py" ]; then
            echo "folder=." >> $GITHUB_ENV
          elif [ -f "$GITHUB_WORKSPACE/daddylive/scraper.py" ]; then
            echo "folder=daddylive" >> $GITHUB_ENV
          else
            echo "scraper.py not found!"
            exit 1
          fi

      # ----------------------
      # Run scraper
      # ----------------------
      - name: Run scraper
        run: |
          echo "Running scraper from folder: ${{ env.folder }}"
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/${{ env.folder }}"
          python ${{ env.folder }}/scraper.py

      # ----------------------
      # Commit and push changes
      # ----------------------
      - name: Commit and push updated playlist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add out.m3u8 tvg-ids.txt || true
          git commit -m "Update M3U8 playlist" || echo "No changes to commit"
          git push
